---
title: "Raincloud plot"
output: html_notebook
---

Below, I will also make a Raincloud plot to see how these scores change over time. No more distinction is made here between the two replicates (morning/afternoon) for visibility reasons.

I first import a few additional packages

```{r, message = FALSE}
    library(caTools)
    library(bitops)
    library(cowplot)
    library(dplyr)
    library(readr)
    library(grid)
```

I change my working directory to have access to the R files from this GitHub repository: https://github.com/RainCloudPlots/RainCloudPlots/tree/master/tutorial_R. 

```{r, message = FALSE}
  # Set working directory
    setwd("/Users/benka/OneDrive/Documents/GitHub/RainCloudPlots/tutorial_R")


    source("R_rainclouds.R")
    source("summarySE.R")
    source("simulateData.R")
```

```{r, message = FALSE}
 
    # This is fake data
    df <- rbind(Travelled.distance, Travelled.distance, Travelled.distance)
    df$Dist <- c(Travelled.distance$Dist, Travelled.distance$Dist/2, Travelled.distance$Dist/3)
    df$time <- c(rep(c("W1"), times = 100), rep(c("W2"), times = 100), rep(c("W3"), times = 100))
    

    # Summary statistics
    sumrepdat <- summarySE(df, measurevar = "Dist", groupvars=c("Treatment_seq", "time"))    
    
    # General information about the plot
    ggplot(df, aes(x = time, y = Dist, fill = Treatment_seq)) + 
      
      # Layer 1 - The half-violins to show densities
      geom_flat_violin(aes(fill = Treatment_seq), 
                       position = position_nudge(x = .1, y = 0), 
                       adjust = 2, trim = FALSE, alpha = .6, 
                       colour = NA) + 
      
      # Layer 2 - All the individual data points
      geom_point(aes(x = time,
                     group = id,
                     y = Dist, 
                     colour = Treatment_seq), 
                     position = position_dodge(width = .1), 
                     size = 1, shape = 19, alpha = 0.4) + 
      
      # Layer 3 - These individual data points are linked together by thin lines
      geom_line(aes(group = id
                ,colour = Treatment_seq
                ), linetype = 1,
                alpha = 0.1, size = 0.5, 
                #colour = "gray",
                position = position_dodge(width = .1)) +


      

      # Layer 5 - A line linking these means
      geom_line(data = sumrepdat, aes(y =  Dist_mean, group = Treatment_seq, 
                                      colour = Treatment_seq), linetype = 1, size = 1) +
      
      # Layer 6 - A mean per treatment sequence
      geom_point(data = sumrepdat, aes(y =  Dist_mean, group = Treatment_seq, 
                                       colour = Treatment_seq), shape = 19, size = 2) +
 
      # Layer 6' - SE/SD bars
      #geom_errorbar(data = sumrepdat, aes( 
      #  y =  Dist_mean, group = Treatment_seq, 
      #  colour = Treatment_seq, ymin =  Dist_mean-sd, 
      #  ymax =  Dist_mean+se), width = 0.05, size = 1.2) +
      
      
      # Define the colours 
      scale_colour_manual(values=c("#6e67b5", "#b3d6e6", "#f7bd6a", "#eb676e")) + 
      scale_fill_manual(values=c("#6e67b5", "#b3d6e6", "#f7bd6a", "#eb676e"))+
      
      # Define the theme
      theme_cowplot()

```
