---
title: "Package workflow"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{my-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This package aims at providing a efficient workflow for extracting, formatting and analyzing data from PIT / RFID readers to study animal behavior in experimental settings. A schematic version of this vignette is available in the \emph{StalkeR cheat sheet}.

# Format data

Before starting to use the \emph{StalkeR} package functions, you have to format and organize your data in a certain way. The unit of the \emph{StalkeR} is a data frame containing _reads_ for one _experimental block_. This means that in this data frame, every row is one read, containing information about the individual id, the antenna it has been read at, and the exact time at which it has been read. An experimental block represents a unit limited in space and time, containing reads from interacting organisms. For instance, if you work with birds, an experimental block can be one enclosure with several animals interacting together. If you work with fishes, an experimental block might be a pond/aquarium containing a group of fish. 
What is not _one_ experimental block:

- An enclosures in which a series of birds (_e.g._, ID_1, ID_2 and ID_3) have been tested for during day 1, and in which another set of birds (_e.g._ ID_4, ID_5, ID_6) have been tested during day 2. In this case, day 1 represents one experimental block, and day 2 represents a second one. 
- Two aquariums in which antennas are installed during the same day. The individuals of aquarium 1 (_e.g._, ID_A, ID_B and ID_C) can only interact together, and cannot interact with the individuals of aquarium 2 (_e.g._ ID_D, ID_E, ID_F), and inversely. In this case, the two aquariums represent 


```{r setup}
library(pondr)
```
